# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anubis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  stripPrefix:
    prefixes:
      - "/api"
---

# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-ide
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anubis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  stripPrefix:
    prefixes:
      - "/ide"
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.api.public
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  {{- if not .Values.debug }}
  entryPoints:
  - websecure
  {{- else }}
  entryPoints:
  - web
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/api/`)
    middlewares:
    - name: strip-api
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis-api
      port: 5000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

# Public Ingress Route /*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anubis
    component: web
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  {{- if .Values.debug }}
  entryPoints:
    - web
  {{- else }}
  entryPoints:
    - websecure
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: anubis-web
      port: 3000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

# Public Ingress Route anubis.osiris.services/ide/
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.theia.public
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: theia
    component: proxy
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  {{- if .Values.debug }}
  entryPoints:
    - web
  {{- else }}
  entryPoints:
    - websecure
  {{- end }}
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/ide/`)
    middlewares:
    - name: strip-ide
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis-theia-proxy
      port: 5000
  - kind: Rule
    match: Host(`ide8000.{{ .Values.domain }}`)
    services:
    - name: anubis-theia-proxy
      port: 5000
  {{- if not .Values.debug }}
  tls:
    certResolver: le
  {{- end }}
---

{{- if not .Values.debug }}
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-new
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anubis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  redirectRegex:
    regex: ^https://anubis.osiris.services/(.*)
    replacement: https://anubis-lms.io/${1}
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.redirect.public
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: theia
    component: proxy
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`anubis.osiris.services`)
    middlewares:
    - name: redirect-to-new
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis-web
      port: 3000
  tls:
    certResolver: le
{{- end }}