# Global Settings
debug: false
rollingUpdates: true
healthChecks: true
domain: "anubis-lms.io"
vpnOnly: false
imagePullPolicy: "Always"
imagePullSecret: "anubis"


###############################################################################
# Deployments with Services

# Main anubis api
api:
  replicas: 2
  workers: 2
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"
  image: "registry.digitalocean.com/anubis/api"
  tag: "latest"

# Anubis web static
web:
  replicas: 2
  image: "registry.digitalocean.com/anubis/web"
  tag: "latest"

# API for submission pipeline reporting
pipeline_api:
  replicas: 1
  workers: 1

# Theia IDE proxy and poller
theia:
  enable: true

  # theia-poller deployment
  poller:
    replicas: 1

  # theia-proxy deployment
  proxy:
    replicas: 2
    image: "registry.digitalocean.com/anubis/theia-proxy"
    tag: "latest"

# Discord Bot
discordbot:
  enable: true
  replicas: 1

###############################################################################



###############################################################################
# Cron Jobs
reaper:
  enable: true
  suspend: false
  schedule: "*/5 * * * *"

daily_cleanup:
  enable: true
  suspend: false
  schedule: "0 4 * * *"  # 4AM

autograde_recalculate:
  enable: true
  suspend: false
  schedule: "*/30 * * * *"

visuals:
  enable: true
  suspend: false
  schedule: "*/5 * * * *"

backup:
  enable: true
  suspend: false
  schedule: "0 0 * * *" # Midnight
  secretName: anubis-backup-creds
###############################################################################


###############################################################################
# RPC Pools
rpc:
  replicas: 1
  queues: ["default", "theia", "regrade"]
###############################################################################


###############################################################################
# Horizontal Pod Autoscaling
hpa:
  enable: true
  rpc:
  - name: rpc-default
  - name: rpc-theia
  - name: rpc-regrade
###############################################################################

